apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag3-may1-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag3-may1-1:2f3a30baa45b1fa7d1d5aaf45afc55b3d1865842@sha256:6d888ebb6b287d1d0151e634e09638213ad635ed2f4138835c5e21ee1fcdde45 # use pre-built to bootstrap
          name: app-inference
